### ISSUE TITLE
Interface support for consistency of set of statements

### ISSUE THREAD

**Issue by trevorsmith772** [cs481-ekh/s22-truth-tables#116]
Alter table interface to have support for the problem type: consistency of a set of statements

References #128 

![Screen Shot 2022-03-16 at 9 10 15 PM](https://user-images.githubusercontent.com/70557597/158729008-b185d79e-8d3c-4c1e-a2eb-660ec4c29d33.png)

**Comment by DystopianNightmare** [comment]
2 hours
