### ISSUE TITLE
Question management 

### ISSUE THREAD

**Issue by BertoCisneros** [cs481-ekh/s22-truth-tables#60]
As an admin user, I would like easy access to a page that allows me to see all questions currently in the database, and the option to delete these questions.

**Comment by DystopianNightmare** [comment]
Is this completed and can be closed or is there additional work beyond styling?

**Comment by BertoCisneros** [comment]
I'm looking at the task now and I think it's either complete or other things need to be done to complete. I know we talked about having the questions available to all, but the delete option would only be available to admin. The 'manage questions' button only is available to the admin user right now so this task may not have needed to be created in the first place.

**Comment by BertoCisneros** [comment]
This task is no longer necessary

**Comment by trevorsmith772** [comment]
Task is reopened and will be reformatted to be a story with its own separate tasks
