### ISSUE TITLE
parserV3 bugs

### ISSUE THREAD

**Issue by DystopianNightmare** [cs481-ekh/s22-truth-tables#67]
Parser should not have bugs
references #54

**Comment by trevorsmith772** [comment]
![Screen Shot 2022-03-03 at 9 54 27 PM](https://user-images.githubusercontent.com/70557597/156702172-f46bde8d-107a-4c50-a9c7-8c47b64d8fba.png)

Red boxes show incorrect outputs

**Comment by BertoCisneros** [comment]
<img width="725" alt="Screen Shot 2022-03-03 at 9 54 11 PM" src="https://user-images.githubusercontent.com/67291148/156702501-c9552ed6-e852-425e-92ea-940a1dcb21d1.png">

Incorrect values in red circles

I think this has been resolved

**Comment by DystopianNightmare** [comment]
A v (B v (C v D)) - resolved
